inherit_gem:
  rubocop-shopify: rubocop.yml

inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Max: 100
  Exclude:
    - db/**/*
    - config/**/*
    - bin/**/*
    - Gemfile

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Style/Documentation:
  Enabled: false

Layout/IndentationWidth:
  Width: 2

Naming/MethodName:
  Enabled: true
  EnforcedStyle: snake_case #default

Naming/ClassAndModuleCamelCase:
  EnforcedStyle: always
